-- Generated by unmodified Deadpan f15ad742bf1e0ec47981bc3416d239760abc9621.
-- Includes shrink, growth, redo, abandoned branch, Repeat subtree, and pending redo.
PRAGMA application_id=1146113585;
PRAGMA user_version=1;
BEGIN TRANSACTION;
CREATE TABLE history (
            id INTEGER PRIMARY KEY,
            parent_id INTEGER REFERENCES history(id),
            revision_id TEXT NOT NULL REFERENCES revisions(id),
            request TEXT NOT NULL CHECK (json_valid(request)),
            edit TEXT NOT NULL CHECK (json_valid(edit))
        ) STRICT;
INSERT INTO "history" VALUES(1,NULL,'v1-insert','{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","expected_revision":"c75fc79f-a09c-4163-92d4-4f15be124866","new_revision":"v1-insert","command":{"command":"insert","parent":"e3aa686a-1b41-4040-b3ad-408be78f9a4e","index":0,"subtree":{"root":"hold","nodes":{"hold":{"label":"Pause","kind":{"type":"hold","recipe":{"duration":12,"video":{"type":"background"},"audio":{"type":"silence"}}}}}}}}','{"forward":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"c75fc79f-a09c-4163-92d4-4f15be124866","to_revision":"v1-insert","nodes":{"e3aa686a-1b41-4040-b3ad-408be78f9a4e":{"before":{"label":"Sequence","kind":{"type":"sequence","children":[]}},"after":{"label":"Sequence","kind":{"type":"sequence","children":["hold"]}}},"hold":{"before":null,"after":{"label":"Pause","kind":{"type":"hold","recipe":{"duration":12,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"inverse":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-insert","to_revision":"c75fc79f-a09c-4163-92d4-4f15be124866","nodes":{"e3aa686a-1b41-4040-b3ad-408be78f9a4e":{"before":{"label":"Sequence","kind":{"type":"sequence","children":["hold"]}},"after":{"label":"Sequence","kind":{"type":"sequence","children":[]}}},"hold":{"before":{"label":"Pause","kind":{"type":"hold","recipe":{"duration":12,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":null}},"assets":{}},"changed_ids":["e3aa686a-1b41-4040-b3ad-408be78f9a4e","hold"],"duration_delta":12,"description":"Insert beats"}');
INSERT INTO "history" VALUES(2,1,'v1-wrap','{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","expected_revision":"v1-insert","new_revision":"v1-wrap","command":{"command":"wrap_repeat","node":"hold","id":"repeat","plays":3,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}','{"forward":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-insert","to_revision":"v1-wrap","nodes":{"e3aa686a-1b41-4040-b3ad-408be78f9a4e":{"before":{"label":"Sequence","kind":{"type":"sequence","children":["hold"]}},"after":{"label":"Sequence","kind":{"type":"sequence","children":["repeat"]}}},"repeat":{"before":null,"after":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":3,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"inverse":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-wrap","to_revision":"v1-insert","nodes":{"e3aa686a-1b41-4040-b3ad-408be78f9a4e":{"before":{"label":"Sequence","kind":{"type":"sequence","children":["repeat"]}},"after":{"label":"Sequence","kind":{"type":"sequence","children":["hold"]}}},"repeat":{"before":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":3,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":null}},"assets":{}},"changed_ids":["e3aa686a-1b41-4040-b3ad-408be78f9a4e","repeat"],"duration_delta":28,"description":"Wrap repeat"}');
INSERT INTO "history" VALUES(3,2,'v1-shrink','{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","expected_revision":"v1-wrap","new_revision":"v1-shrink","command":{"command":"set_repeat","node":"repeat","plays":2,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}','{"forward":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-wrap","to_revision":"v1-shrink","nodes":{"repeat":{"before":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":3,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":2,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"inverse":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-shrink","to_revision":"v1-wrap","nodes":{"repeat":{"before":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":2,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":3,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"changed_ids":["repeat"],"duration_delta":-14,"description":"Set repeat parameters"}');
INSERT INTO "history" VALUES(4,3,'v1-grow','{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","expected_revision":"v1-shrink","new_revision":"v1-grow","command":{"command":"set_repeat","node":"repeat","plays":4,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}','{"forward":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-shrink","to_revision":"v1-grow","nodes":{"repeat":{"before":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":2,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":4,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"inverse":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-grow","to_revision":"v1-shrink","nodes":{"repeat":{"before":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":4,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":2,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"changed_ids":["repeat"],"duration_delta":28,"description":"Set repeat parameters"}');
INSERT INTO "history" VALUES(5,3,'v1-branch','{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","expected_revision":"5883159e-7295-40d2-8480-bc3302aa00d5","new_revision":"v1-branch","command":{"command":"set_repeat","node":"repeat","plays":5,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}','{"forward":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"5883159e-7295-40d2-8480-bc3302aa00d5","to_revision":"v1-branch","nodes":{"repeat":{"before":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":2,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":5,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"inverse":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-branch","to_revision":"5883159e-7295-40d2-8480-bc3302aa00d5","nodes":{"repeat":{"before":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":5,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":{"label":"Repeat","kind":{"type":"repeat","child":"hold","plays":2,"gap":{"duration":2,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"changed_ids":["repeat"],"duration_delta":42,"description":"Set repeat parameters"}');
INSERT INTO "history" VALUES(6,5,'v1-subtree','{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","expected_revision":"v1-branch","new_revision":"v1-subtree","command":{"command":"insert","parent":"e3aa686a-1b41-4040-b3ad-408be78f9a4e","index":1,"subtree":{"root":"insert-repeat","nodes":{"insert-repeat":{"label":"Imported repeat","kind":{"type":"repeat","child":"second-hold","plays":2,"gap":null}},"second-hold":{"label":"Pause","kind":{"type":"hold","recipe":{"duration":4,"video":{"type":"background"},"audio":{"type":"silence"}}}}}}}}','{"forward":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-branch","to_revision":"v1-subtree","nodes":{"e3aa686a-1b41-4040-b3ad-408be78f9a4e":{"before":{"label":"Sequence","kind":{"type":"sequence","children":["repeat"]}},"after":{"label":"Sequence","kind":{"type":"sequence","children":["repeat","insert-repeat"]}}},"insert-repeat":{"before":null,"after":{"label":"Imported repeat","kind":{"type":"repeat","child":"second-hold","plays":2,"gap":null}}},"second-hold":{"before":null,"after":{"label":"Pause","kind":{"type":"hold","recipe":{"duration":4,"video":{"type":"background"},"audio":{"type":"silence"}}}}}},"assets":{}},"inverse":{"project_id":"8c2dc8c8-9447-46d8-8185-067dcc23d65b","from_revision":"v1-subtree","to_revision":"v1-branch","nodes":{"e3aa686a-1b41-4040-b3ad-408be78f9a4e":{"before":{"label":"Sequence","kind":{"type":"sequence","children":["repeat","insert-repeat"]}},"after":{"label":"Sequence","kind":{"type":"sequence","children":["repeat"]}}},"insert-repeat":{"before":{"label":"Imported repeat","kind":{"type":"repeat","child":"second-hold","plays":2,"gap":null}},"after":null},"second-hold":{"before":{"label":"Pause","kind":{"type":"hold","recipe":{"duration":4,"video":{"type":"background"},"audio":{"type":"silence"}}}},"after":null}},"assets":{}},"changed_ids":["e3aa686a-1b41-4040-b3ad-408be78f9a4e","insert-repeat","second-hold"],"duration_delta":8,"description":"Insert beats"}');
CREATE TABLE redo (
            position INTEGER PRIMARY KEY,
            history_id INTEGER NOT NULL REFERENCES history(id)
        ) STRICT;
INSERT INTO "redo" VALUES(1,6);
INSERT INTO "redo" VALUES(2,5);
CREATE TABLE revisions (
            id TEXT PRIMARY KEY,
            parent_id TEXT REFERENCES revisions(id),
            kind TEXT NOT NULL CHECK (kind IN ('initial','edit','undo','redo')),
            document TEXT NOT NULL CHECK (json_valid(document))
        ) STRICT;
INSERT INTO "revisions" VALUES('c75fc79f-a09c-4163-92d4-4f15be124866',NULL,'initial','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "c75fc79f-a09c-4163-92d4-4f15be124866",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": []
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('v1-insert','c75fc79f-a09c-4163-92d4-4f15be124866','edit','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "v1-insert",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "hold"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('v1-wrap','v1-insert','edit','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "v1-wrap",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 3,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('v1-shrink','v1-wrap','edit','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "v1-shrink",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 2,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('v1-grow','v1-shrink','edit','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "v1-grow",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 4,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('e83c0816-2686-4c5d-91ec-dade545d5d0b','v1-grow','undo','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "e83c0816-2686-4c5d-91ec-dade545d5d0b",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 2,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('1fc59810-16bf-44ee-a473-661c60f0e7f9','e83c0816-2686-4c5d-91ec-dade545d5d0b','redo','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "1fc59810-16bf-44ee-a473-661c60f0e7f9",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 4,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('5883159e-7295-40d2-8480-bc3302aa00d5','1fc59810-16bf-44ee-a473-661c60f0e7f9','undo','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "5883159e-7295-40d2-8480-bc3302aa00d5",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 2,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('v1-branch','5883159e-7295-40d2-8480-bc3302aa00d5','edit','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "v1-branch",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 5,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('v1-subtree','v1-branch','edit','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "v1-subtree",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat",
          "insert-repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "insert-repeat": {
      "label": "Imported repeat",
      "kind": {
        "type": "repeat",
        "child": "second-hold",
        "plays": 2,
        "gap": null
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 5,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "second-hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 4,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('6e18bc82-1f75-4ab7-a935-e777790999ab','v1-subtree','undo','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "6e18bc82-1f75-4ab7-a935-e777790999ab",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 5,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
INSERT INTO "revisions" VALUES('083d6755-44c8-4911-9c35-b9b4189d55df','6e18bc82-1f75-4ab7-a935-e777790999ab','undo','{
  "schema_version": 1,
  "project_id": "8c2dc8c8-9447-46d8-8185-067dcc23d65b",
  "revision_id": "083d6755-44c8-4911-9c35-b9b4189d55df",
  "presentation_basis": {
    "width": 1920,
    "height": 1080,
    "frame_rate": {
      "numerator": 30000,
      "denominator": 1001
    },
    "color_policy": "sdr_rec709"
  },
  "root": "e3aa686a-1b41-4040-b3ad-408be78f9a4e",
  "nodes": {
    "e3aa686a-1b41-4040-b3ad-408be78f9a4e": {
      "label": "Sequence",
      "kind": {
        "type": "sequence",
        "children": [
          "repeat"
        ]
      }
    },
    "hold": {
      "label": "Pause",
      "kind": {
        "type": "hold",
        "recipe": {
          "duration": 12,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    },
    "repeat": {
      "label": "Repeat",
      "kind": {
        "type": "repeat",
        "child": "hold",
        "plays": 2,
        "gap": {
          "duration": 2,
          "video": {
            "type": "background"
          },
          "audio": {
            "type": "silence"
          }
        }
      }
    }
  },
  "assets": {}
}
');
CREATE TABLE state (
            singleton INTEGER PRIMARY KEY CHECK (singleton=1),
            head_revision TEXT NOT NULL REFERENCES revisions(id),
            cursor INTEGER REFERENCES history(id)
        ) STRICT;
INSERT INTO "state" VALUES(1,'083d6755-44c8-4911-9c35-b9b4189d55df',3);
CREATE INDEX revision_parent ON revisions(parent_id);
CREATE INDEX history_revision ON history(revision_id);
COMMIT;
