//! Native Camera integration. The document stays immutable while presentation
//! replaces one evaluated operation on its already decoded picture.

use crate::navigation::FramingAction;
use crate::navigation::camera::{
    CameraDraft, CameraEffect, CameraKey, CameraPanSteps, CameraPhase,
};
use deadpan_core::{ExactRatio, Framing, FramingCurve, FramingPose, FramingValue, InstancePath};
use deadpan_render::FramingLayer;

use super::*;

#[derive(Debug, PartialEq, Eq)]
pub(super) enum KeyDispatch {
    Native,
    Global,
    Draft(CameraKey),
    Deferred(CameraKey),
}

/// Camera has already consumed the prefix as editor commands. A newly focused
/// TextEdit must receive only later input, never text generated by that prefix.
pub(super) fn retain_field_input_suffix(context: &egui::Context, suffix: &[egui::Event]) {
    context.input_mut(|input| {
        input.events.clear();
        input.events.extend_from_slice(suffix);
    });
}

pub(super) fn dispatch_key(
    key: egui::Key,
    modifiers: egui::Modifiers,
    text: bool,
    ime: bool,
    repeat: bool,
    field: bool,
    activation: bool,
) -> KeyDispatch {
    if ime {
        return KeyDispatch::Native;
    }
    if field {
        if modifiers.command || modifiers.mac_cmd || modifiers.ctrl {
            // Native field undo/redo, selection and clipboard shortcuts must
            // never reach project history. Only explicit project lifecycle
            // shortcuts leave text entry; they cancel the Camera draft.
            return if (modifiers.command || modifiers.mac_cmd)
                && matches!(key, egui::Key::N | egui::Key::O | egui::Key::I)
            {
                KeyDispatch::Global
            } else {
                KeyDispatch::Native
            };
        }
        if modifiers == egui::Modifiers::NONE {
            let deferred = match key {
                egui::Key::ArrowUp => Some(CameraKey::Arrow(navigation::camera::Direction::Up)),
                egui::Key::ArrowDown => Some(CameraKey::Arrow(navigation::camera::Direction::Down)),
                egui::Key::Escape if !repeat => Some(CameraKey::Cancel),
                _ => None,
            };
            if let Some(key) = deferred {
                return KeyDispatch::Deferred(key);
            }
        }
        return KeyDispatch::Native;
    }
    if modifiers.command || modifiers.mac_cmd || modifiers.ctrl {
        return KeyDispatch::Global;
    }
    if text || activation {
        return KeyDispatch::Native;
    }
    if key == egui::Key::Questionmark {
        return KeyDispatch::Global;
    }
    KeyDispatch::Draft(
        navigation::route_camera_key(key, modifiers, text, ime, repeat).unwrap_or(CameraKey::Other),
    )
}

pub(super) struct CameraPending {
    action: FramingAction,
    session: u64,
    revision: RevisionId,
    node: NodeId,
    cursor: u64,
}

pub(super) struct CameraSession {
    session: u64,
    revision: RevisionId,
    scope: InstancePath,
    ticket: Ticket,
    cursor: u64,
    entry: Option<Framing>,
    entry_pose: Option<FramingPose>,
    draft: CameraDraft,
    steps: CameraPanSteps,
    targets: Vec<(u8, &'static str, Option<[ExactRatio; 2]>)>,
    committing: bool,
    fields: super::camera_fields::CameraFields,
    field_keys: Vec<CameraKey>,
    field_error: Option<String>,
    local_position: ExactRatio,
    duration: deadpan_core::FrameDuration,
}

fn projected_ratio(value: f64) -> Result<ExactRatio, String> {
    // Source-to-canvas projection is the declared f64 geometry boundary. Admit
    // finite representable values, then quantize once to the core's Q32 grid.
    if !value.is_finite() || value.abs() > 1_000_000_000.0 {
        return Err("This source projection exceeds Camera's numeric range.".into());
    }
    ExactRatio::new(
        (value * deadpan_core::FRAMING_NUMERIC_SCALE as f64).round_ties_even() as i128,
        i128::from(deadpan_core::FRAMING_NUMERIC_SCALE),
    )
    .map_err(|error| error.to_string())
}

fn projected_point(value: [f64; 2]) -> Result<[ExactRatio; 2], String> {
    Ok([projected_ratio(value[0])?, projected_ratio(value[1])?])
}

/// Move the entire authored camera path, including cubic controls. Editing a
/// currently evaluated pose must not silently collapse an existing creep.
fn adjusted_framing(
    entry: Option<&Framing>,
    from: FramingPose,
    to: FramingPose,
    reset: bool,
) -> Result<Option<Framing>, String> {
    if !reset && from == to {
        return Ok(entry.cloned());
    }
    if reset || entry.is_none() {
        return if to == FramingPose::identity() {
            Ok(None)
        } else {
            Framing::static_pose(to)
                .map(Some)
                .map_err(|error| error.to_string())
        };
    }
    let dx = to
        .center_x
        .checked_sub(from.center_x)
        .map_err(|error| error.to_string())?;
    let dy = to
        .center_y
        .checked_sub(from.center_y)
        .map_err(|error| error.to_string())?;
    let factor = to
        .scale
        .checked_div(from.scale)
        .map_err(|error| error.to_string())?;
    let transform = |pose: &mut FramingPose| -> Result<(), String> {
        let changed = FramingPose {
            center_x: pose
                .center_x
                .checked_add(dx)
                .map_err(|error| error.to_string())?,
            center_y: pose
                .center_y
                .checked_add(dy)
                .map_err(|error| error.to_string())?,
            scale: pose
                .scale
                .checked_mul(factor)
                .map_err(|error| error.to_string())?,
        };
        *pose = changed.quantized().map_err(|error| error.to_string())?;
        Ok(())
    };
    let mut framing = entry.expect("nonempty entry checked").clone();
    match &mut framing.value {
        FramingValue::Static { pose } => transform(pose)?,
        FramingValue::Envelope { envelope } => {
            transform(&mut envelope.initial)?;
            for segment in &mut envelope.segments {
                transform(&mut segment.pose)?;
                if let FramingCurve::Cubic { control1, control2 } = &mut segment.curve {
                    transform(control1)?;
                    transform(control2)?;
                }
            }
        }
    }
    framing.validate().map_err(|error| error.to_string())?;
    Ok(Some(framing))
}

impl CameraSession {
    fn from_picture(
        app: &DeadpanApp,
        pending: CameraPending,
        ticket: Ticket,
    ) -> Result<Self, String> {
        let workspace = app.workspace.as_ref().ok_or("Open a project first.")?;
        let picture = app
            .presentation
            .picture()
            .ok_or("Wait for the stopped picture.")?;
        let frame = picture
            .frame
            .as_ref()
            .ok_or("This beat has no picture to frame.")?;
        let index = picture
            .framing
            .iter()
            .position(|layer| {
                layer.instance.node == pending.node && layer.instance.repeats.is_empty()
            })
            .ok_or("Move the cursor inside the selected root beat to frame it.")?;
        let layer = &picture.framing[index];
        let (width, height) = picture.canvas.ok_or("Camera requires Your edit.")?;
        let render_layers = render_layers(picture)?;
        let geometry = deadpan_render::PictureGeometry::framed(
            frame.metadata(),
            [width, height],
            [width, height],
            FitMode::Fit,
            &render_layers,
        )
        .map_err(|error| error.to_string())?;
        let index = index + usize::from(picture.framing_gap);
        let steps = geometry
            .source_steps(index)
            .map_err(|error| error.to_string())?;
        let mut targets = Vec::new();
        for (number, label, point) in [
            (1, "Center", [0.5, 0.5]),
            (2, "Top left", [0.0, 0.0]),
            (3, "Top right", [1.0, 0.0]),
            (4, "Bottom left", [0.0, 1.0]),
            (5, "Bottom right", [1.0, 1.0]),
        ] {
            let projected = geometry
                .source_to_input(index, point)
                .map_err(|error| error.to_string())?
                .map(projected_point)
                .transpose()?;
            targets.push((number, label, projected));
        }
        let entry_pose = layer.pose;
        Ok(Self {
            session: pending.session,
            revision: pending.revision,
            scope: layer.instance.clone(),
            ticket,
            cursor: pending.cursor,
            entry: workspace.document.nodes()[&pending.node].framing.clone(),
            entry_pose,
            draft: CameraDraft::new(entry_pose.unwrap_or_default())
                .map_err(|error| error.to_string())?,
            steps: CameraPanSteps {
                horizontal: projected_point(steps[0])?,
                vertical: projected_point(steps[1])?,
            },
            targets,
            committing: false,
            fields: super::camera_fields::CameraFields::new(entry_pose.unwrap_or_default()),
            field_keys: Vec::new(),
            field_error: None,
            local_position: layer.local_position,
            duration: layer.duration,
        })
    }

    fn framing(&self, pose: FramingPose, reset: bool) -> Result<Option<Framing>, String> {
        adjusted_framing(
            self.entry.as_ref(),
            self.entry_pose.unwrap_or_default(),
            pose,
            reset,
        )
    }
}

impl DeadpanApp {
    pub(super) fn framing_action(&mut self, action: FramingAction, context: &egui::Context) {
        if self.view != View::Sequence {
            self.error = Some("Camera edits Your edit. The Original stays intact.".into());
            return;
        }
        if self.service.is_busy() || self.dialogs.is_open() {
            self.error = Some("Finish the current project action before framing.".into());
            return;
        }
        self.cancel_camera();
        self.pause_playback();
        self.bindings.clear();
        let Some(workspace) = &self.workspace else {
            return;
        };
        let Some(node) = &self.selected_beat else {
            self.error = Some("Select a root beat to frame.".into());
            return;
        };
        self.camera_pending = Some(CameraPending {
            action,
            session: workspace.session,
            revision: workspace.document.revision_id().clone(),
            node: node.clone(),
            cursor: self.sequence_cursor,
        });
        self.finish_camera_entry(context);
    }

    pub(super) fn finish_camera_entry(&mut self, context: &egui::Context) {
        let Some(pending) = self.camera_pending.as_ref() else {
            return;
        };
        let valid = self.view == View::Sequence
            && self.sequence_cursor == pending.cursor
            && self.selected_beat.as_ref() == Some(&pending.node)
            && self.workspace.as_ref().is_some_and(|workspace| {
                workspace.session == pending.session
                    && workspace.document.revision_id() == &pending.revision
            });
        if !valid {
            self.camera_pending = None;
            return;
        }
        let frame = ProjectFrame(
            self.sequence_cursor
                .min(self.sequence_length().saturating_sub(1)) as i64,
        );
        let Some(ticket) =
            self.presentation
                .stable_sequence_ticket(pending.session, &pending.revision, frame)
        else {
            if !self.presentation.loading() && !self.presentation.needs_render() {
                self.camera_pending = None;
                self.error =
                    Some("Camera needs a successfully displayed picture at the cursor.".into());
            } else {
                self.message = Some("Preparing the stopped picture for framing…".into());
                context.request_repaint();
            }
            return;
        };
        let pending = self.camera_pending.take().expect("pending checked");
        let action = pending.action;
        let session = match CameraSession::from_picture(self, pending, ticket) {
            Ok(session) => session,
            Err(error) => {
                self.error = Some(error);
                return;
            }
        };
        self.error = None;
        self.message = None;
        if action == FramingAction::EnterCamera {
            self.camera = Some(session);
            self.pane = Pane::Viewer;
            context.memory_mut(|memory| memory.request_focus(pane_id(Pane::Viewer)));
        } else {
            let start = session.entry_pose.unwrap_or_default();
            let end = FramingPose {
                scale: ExactRatio::new(27, 20).expect("constant ratio"),
                ..start
            };
            let framing = if action == FramingAction::Creep {
                Framing::creep(start, end, FramingCurve::Smoothstep)
                    .map(Some)
                    .map_err(|error| error.to_string())
            } else {
                // A smash is a constant 1.35× pose, replacing any prior curve.
                Framing::static_pose(end)
                    .map(Some)
                    .map_err(|error| error.to_string())
            };
            match framing {
                Ok(framing) => {
                    self.submit_framing(&session, framing);
                }
                Err(error) => self.error = Some(error),
            }
        }
    }

    fn submit_framing(&mut self, camera: &CameraSession, framing: Option<Framing>) -> bool {
        if framing == camera.entry {
            self.message = Some("Framing is unchanged; no edit was made.".into());
            return true;
        }
        self.submit(ProjectRequest::Edit {
            expected_session: camera.session,
            expected_revision: camera.revision.clone(),
            edit: ProjectEdit::SetFraming {
                node: camera.scope.node.clone(),
                framing,
            },
        })
    }

    pub(super) fn cancel_camera(&mut self) {
        self.camera_pending = None;
        if let Some(camera) = self.camera.take()
            && !camera.committing
        {
            // A newer picture/session already owns presentation if this fails.
            let _ =
                self.presentation
                    .set_framing_pose(camera.ticket, &camera.scope, camera.entry_pose);
        }
        self.bindings.clear();
    }

    pub(super) fn reconcile_camera(&mut self) {
        let Some(camera) = &self.camera else {
            return;
        };
        let valid = self.view == View::Sequence
            && self.sequence_cursor == camera.cursor
            && self.selected_beat.as_ref() == Some(&camera.scope.node)
            && self.workspace.as_ref().is_some_and(|workspace| {
                workspace.session == camera.session
                    && workspace.document.revision_id() == &camera.revision
            });
        if !valid {
            self.cancel_camera();
        } else if camera.committing && !self.service.is_busy() {
            // A rejected command has no new revision. Restore the entry display
            // and leave the service's failure visible; never call the draft saved.
            if let Some(camera) = self.camera.as_mut() {
                camera.committing = false;
            }
            self.cancel_camera();
        }
    }

    pub(super) fn camera_input(&mut self, key: CameraKey, context: &egui::Context) {
        let Some(camera) = &mut self.camera else {
            return;
        };
        if camera.committing {
            return;
        }
        if key == CameraKey::Commit && (!camera.fields.is_valid() || camera.field_error.is_some()) {
            self.error = Some(
                camera
                    .field_error
                    .clone()
                    .or_else(|| camera.fields.error_message().map(str::to_owned))
                    .unwrap_or_else(|| "Correct the Camera fields before applying framing.".into()),
            );
            return;
        }
        let previous = camera.draft.clone();
        let effect = camera.draft.input(key, Some(camera.steps));
        if matches!(
            effect,
            CameraEffect::PoseChanged(_) | CameraEffect::Reset(_)
        ) && let Err(error) = camera.framing(camera.draft.pose(), camera.draft.reset_requested())
        {
            camera.draft = previous;
            self.error = Some(error);
            return;
        }
        if matches!(
            effect,
            CameraEffect::PoseChanged(_) | CameraEffect::Reset(_)
        ) {
            camera.fields.sync(camera.draft.pose());
            camera.field_error = None;
        }
        self.camera_effect(effect, context);
    }

    fn camera_effect(&mut self, effect: CameraEffect, context: &egui::Context) {
        match effect {
            CameraEffect::None | CameraEffect::RefreshTargets | CameraEffect::TargetsClosed => {}
            CameraEffect::Unchanged => {
                self.cancel_camera();
                self.message = Some("Framing is unchanged; no edit was made.".into());
            }
            CameraEffect::CycleField { reverse } => {
                if let Some(camera) = &self.camera {
                    let mut ids = vec![pane_id(Pane::Viewer)];
                    ids.extend(camera.fields.ids().iter().copied());
                    let current = context
                        .memory(|memory| memory.focused())
                        .and_then(|id| ids.iter().position(|candidate| *candidate == id))
                        .unwrap_or(0);
                    let next = if reverse {
                        (current + ids.len() - 1) % ids.len()
                    } else {
                        (current + 1) % ids.len()
                    };
                    context.memory_mut(|memory| memory.request_focus(ids[next]));
                }
            }
            CameraEffect::AdjustField { direction, count } => {
                if let Some(camera) = self.camera.as_mut() {
                    for digit in count.to_string().bytes() {
                        camera.draft.input(CameraKey::Digit(digit - b'0'), None);
                    }
                }
                self.camera_input(
                    CameraKey::Pan {
                        direction,
                        coarse: false,
                    },
                    context,
                );
            }
            CameraEffect::SelectTarget(number) => self.camera_target(number, context),
            CameraEffect::PoseChanged(pose) | CameraEffect::Reset(pose) => {
                let Some(camera) = &self.camera else {
                    return;
                };
                match camera.framing(pose, camera.draft.reset_requested()) {
                    Ok(framing) => {
                        let evaluated = framing
                            .as_ref()
                            .map(|framing| framing.evaluate(camera.local_position, camera.duration))
                            .transpose()
                            .map_err(|error| error.to_string());
                        if let Err(error) = evaluated.and_then(|pose| {
                            self.presentation
                                .set_framing_pose(camera.ticket, &camera.scope, pose)
                        }) {
                            self.error = Some(error);
                        } else {
                            self.error = None;
                        }
                    }
                    Err(error) => self.error = Some(error),
                }
            }
            CameraEffect::Commit { pose, reset } => {
                let Some(mut camera) = self.camera.take() else {
                    return;
                };
                match camera.framing(pose, reset) {
                    Ok(framing) if framing == camera.entry => {
                        let _ = self.presentation.set_framing_pose(
                            camera.ticket,
                            &camera.scope,
                            camera.entry_pose,
                        );
                        self.message = Some("Framing is unchanged; no edit was made.".into());
                    }
                    Ok(framing) => {
                        if self.submit_framing(&camera, framing) {
                            camera.committing = true;
                            self.camera = Some(camera);
                        } else {
                            let _ = self.presentation.set_framing_pose(
                                camera.ticket,
                                &camera.scope,
                                camera.entry_pose,
                            );
                        }
                    }
                    Err(error) => {
                        let _ = self.presentation.set_framing_pose(
                            camera.ticket,
                            &camera.scope,
                            camera.entry_pose,
                        );
                        self.error = Some(error);
                    }
                }
            }
            CameraEffect::Cancel => {
                self.cancel_camera();
                context.memory_mut(|memory| memory.request_focus(pane_id(Pane::Viewer)));
            }
            CameraEffect::Rejected(error) => self.error = Some(error.to_string()),
        }
        context.request_repaint();
    }

    fn camera_target(&mut self, number: u8, context: &egui::Context) {
        let Some(camera) = &mut self.camera else {
            return;
        };
        let Some((_, _, Some(center))) = camera.targets.iter().find(|target| target.0 == number)
        else {
            camera.draft.target_unavailable(number);
            self.error = Some("That target is outside the selected beat's visible input.".into());
            return;
        };
        let pose = FramingPose {
            center_x: center[0],
            center_y: center[1],
            ..camera.draft.pose()
        };
        if let Err(error) = camera.framing(pose, camera.draft.reset_requested()) {
            self.error = Some(error);
            return;
        }
        let effect = camera.draft.choose_target(number, pose);
        if matches!(effect, CameraEffect::PoseChanged(_)) {
            camera.fields.sync(camera.draft.pose());
            camera.field_error = None;
        }
        self.camera_effect(effect, context);
    }

    pub(super) fn camera_field_focused(&self, context: &egui::Context) -> bool {
        self.camera
            .as_ref()
            .is_some_and(|camera| camera.fields.owns_focus(context))
    }

    // TextEdit must see this frame's native text/IME before field arrows or
    // Escape are interpreted by Camera. Enter first finishes the native field.
    pub(super) fn defer_camera_field_key(&mut self, key: CameraKey) {
        if let Some(camera) = &mut self.camera {
            camera.draft.clear_count();
            camera.field_keys.push(key);
        }
    }

    pub(super) fn camera_overlay(&self, ui: &egui::Ui, canvas: egui::Rect) {
        let Some(camera) = &self.camera else {
            return;
        };
        if canvas.width() < 24.0 || canvas.height() < 24.0 {
            return;
        }
        if self.presentation.needs_render()
            || self.presentation.loading()
            || !self.presentation.can_render()
        {
            return;
        }
        let Some(picture) = self.presentation.picture() else {
            return;
        };
        let Some(frame) = &picture.frame else {
            return;
        };
        let Some((width, height)) = picture.canvas else {
            return;
        };
        let Ok(layers) = render_layers(picture) else {
            return;
        };
        let Ok(geometry) = deadpan_render::PictureGeometry::framed(
            frame.metadata(),
            [width, height],
            [width, height],
            FitMode::Fit,
            &layers,
        ) else {
            return;
        };
        let painter = ui.painter().with_clip_rect(canvas);
        let center = canvas.center();
        let stroke = egui::Stroke::new(1.0, style::LAVENDER);
        painter.line_segment(
            [center - egui::vec2(7.0, 0.0), center + egui::vec2(7.0, 0.0)],
            stroke,
        );
        painter.line_segment(
            [center - egui::vec2(0.0, 7.0), center + egui::vec2(0.0, 7.0)],
            stroke,
        );
        if camera.draft.phase() == CameraPhase::TargetPicker {
            for (number, point) in [
                (1, [0.5, 0.5]),
                (2, [0.0, 0.0]),
                (3, [1.0, 0.0]),
                (4, [0.0, 1.0]),
                (5, [1.0, 1.0]),
            ] {
                if let Ok(Some(point)) = geometry.source_to_canvas(point) {
                    let anchor = canvas.min
                        + egui::vec2(
                            point[0] as f32 * canvas.width(),
                            point[1] as f32 * canvas.height(),
                        );
                    let badge = anchor.clamp(
                        canvas.min + egui::vec2(12.0, 12.0),
                        canvas.max - egui::vec2(12.0, 12.0),
                    );
                    painter.line_segment([anchor, badge], stroke);
                    painter.circle_filled(badge, 9.0, style::LAVENDER);
                    painter.text(
                        badge,
                        egui::Align2::CENTER_CENTER,
                        number.to_string(),
                        egui::FontId::monospace(12.0),
                        style::CANVAS,
                    );
                }
            }
        }
    }

    pub(super) fn camera_footer(&self, ui: &mut egui::Ui) {
        let Some(camera) = &self.camera else {
            return;
        };
        ui.horizontal_wrapped(|ui| {
            ui.label(
                egui::RichText::new("CAMERA")
                    .monospace()
                    .strong()
                    .color(style::LAVENDER),
            );
            ui.separator();
            let label = self
                .workspace
                .as_ref()
                .and_then(|workspace| workspace.document.nodes().get(&camera.scope.node))
                .map_or("Selected beat", |node| node.label.as_str());
            ui.label(format!("{label} · Root beat"));
            ui.label(if camera.committing {
                "Saving framing…"
            } else {
                "Draft · unsaved"
            });
            if camera.draft.count_overflowed() {
                ui.colored_label(ui.visuals().error_fg_color, "Count too large");
            } else if let Some(count) = camera.draft.pending_count() {
                style::keycap(ui, &count.to_string());
            }
            if self.presentation.needs_render() {
                ui.spinner();
                ui.weak("Updating picture");
            }
        });
        ui.horizontal_wrapped(|ui| {
            if camera.draft.phase() == CameraPhase::TargetPicker {
                style::key_hint(ui, "1–5", "source target");
                style::key_hint(ui, "f", "back");
            } else {
                style::key_hint(ui, "h j k l", "move 1%");
                style::key_hint(ui, "H J K L", "move 5%");
                style::key_hint(ui, "+ −", "scale ×1.05");
                style::key_hint(ui, "3+", "three steps");
                style::key_hint(ui, "f", "targets");
                style::key_hint(ui, "Tab", "fields");
                style::key_hint(ui, "Enter", "apply");
            }
            style::key_hint(ui, "r", "reset");
            style::key_hint(ui, "Esc", "cancel");
        });
        if let Some(error) = self
            .error
            .as_deref()
            .or(self.project_error.as_deref())
            .or(self.presentation.error())
        {
            ui.colored_label(ui.visuals().error_fg_color, error);
        }
    }

    pub(super) fn camera_inspector(&mut self, ui: &mut egui::Ui) {
        let Some(mut camera) = self.camera.take() else {
            return;
        };
        let layout = self.workspace_layout(ui);
        let mut proposed = None;
        let mut requested = None;
        let mut target = None;
        egui::Panel::right("workspace-inspector").resizable(false)
            .default_size(layout.inspector).min_size(layout.inspector).max_size(layout.inspector)
            .frame(style::panel()).show(ui, |ui| {
                pane_heading(ui, "FRAMING", camera.fields.owns_focus(ui.ctx()));
                ui.label(egui::RichText::new("Camera · temporary preview").color(style::LAVENDER));
                ui.separator();
                ui.add_enabled_ui(!camera.committing, |ui| {
                    egui::ScrollArea::vertical().id_salt("camera-inspector").show(ui, |ui| {
                        ui.label("Scope: selected root beat");
                        ui.add_space(8.0);
                        ui.add_enabled_ui(camera.draft.phase() == CameraPhase::Adjust, |ui| {
                            proposed = camera.fields.show(ui);
                        });
                        for key in std::mem::take(&mut camera.field_keys) {
                            match key {
                                CameraKey::Arrow(direction) => {
                                    if let Some(result) = camera.fields.adjust_focused(ui.ctx(), direction, 1) {
                                        proposed = Some(result);
                                    }
                                }
                                CameraKey::Cancel => requested = Some(CameraKey::Cancel),
                                _ => {}
                            }
                        }
                        // Validate the complete authored curve before enabling Apply,
                        // including pointer focus changes in this same native batch.
                        if let Some(result) = &proposed {
                            camera.field_error = match result {
                                Ok(pose) => camera.framing(*pose, camera.draft.reset_requested()).err(),
                                Err(error) => Some(error.clone()),
                            };
                        }
                        if let Some(error) = camera.field_error.as_deref().filter(|error| Some(*error) != camera.fields.error_message()) {
                            ui.colored_label(ui.visuals().error_fg_color, error);
                        }
                        ui.add_space(8.0);
                        ui.weak(if camera.draft.phase() == CameraPhase::TargetPicker {
                            "Choose 1–5 or press f to return to adjustment."
                        } else {
                            "Tab moves through fields. Up/Down changes 1%. Enter finishes a field; Enter in the viewer applies the edit."
                        });
                        ui.separator();
                        let curve = !camera.draft.reset_requested() && matches!(camera.entry.as_ref().map(|entry| &entry.value), Some(FramingValue::Envelope { .. }));
                        if curve { ui.label("Existing curve preserved"); ui.weak("Adjustments move and scale its full path. Reset replaces the curve."); }
                        else { ui.label("Static framing"); }
                        if ui.button(if camera.draft.phase() == CameraPhase::TargetPicker { "Close source targets  ·  f" } else { "Choose source target  ·  f" }).clicked() { requested = Some(CameraKey::RefreshTargets); }
                        if camera.draft.phase() == CameraPhase::TargetPicker {
                            for (number, label, center) in &camera.targets {
                                let response = ui.add_enabled(center.is_some(), egui::Button::new(format!("{number}  {label}")).min_size(egui::vec2(ui.available_width(), 28.0)));
                                if response.clicked() { target = Some(*number); }
                                if center.is_none() { response.on_hover_text("This point was clipped by a descendant operation."); }
                            }
                            ui.weak("Center and corners of the upright Original. These are manual positions.");
                        }
                        ui.add_space(12.0);
                        let valid = camera.fields.is_valid() && camera.field_error.is_none() && camera.draft.phase() == CameraPhase::Adjust;
                        if ui.add_enabled(valid, egui::Button::new("Apply  ·  Enter").fill(style::SELECTED).min_size(egui::vec2(ui.available_width(), 30.0))).clicked() { requested = Some(CameraKey::Commit); }
                        if ui.add_sized([ui.available_width(), 28.0], egui::Button::new("Cancel  ·  Esc")).clicked() { requested = Some(CameraKey::Cancel); }
                        if ui.button("Reset framing  ·  r").clicked() { requested = Some(CameraKey::Reset); }
                        ui.add_space(8.0);
                        ui.weak("Timing stays put. Uncovered picture is black.");
                    });
                });
            });
        let effect = proposed.and_then(|result| {
            if camera.field_error.is_none() {
                result.ok().map(|pose| camera.draft.set_pose(pose))
            } else {
                None
            }
        });
        self.camera = Some(camera);
        if let Some(effect) = effect {
            self.camera_effect(effect, ui.ctx());
        }
        if let Some(target) = target {
            self.camera_input(CameraKey::Digit(target), ui.ctx());
        }
        if let Some(key) = requested {
            self.camera_input(key, ui.ctx());
        }
    }
}

pub(super) fn render_layers(picture: &crate::worker::Picture) -> Result<Vec<FramingLayer>, String> {
    let mut layers = Vec::with_capacity(picture.framing.len() + usize::from(picture.framing_gap));
    if picture.framing_gap {
        layers.push(FramingLayer::identity());
    }
    for layer in &picture.framing {
        layers.push(match &layer.pose {
            Some(pose) => FramingLayer::new([pose.center_x, pose.center_y], pose.scale)
                .map_err(|error| error.to_string())?,
            None => FramingLayer::identity(),
        });
    }
    Ok(layers)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tab_into_camera_fields_does_not_retype_an_earlier_count() {
        fn draw_with_prefix(retain_suffix: bool) -> Option<Result<FramingPose, String>> {
            let context = egui::Context::default();
            let mut fields =
                super::super::camera_fields::CameraFields::new(FramingPose::identity());
            let mut result = None;
            let mut output = context.run_ui(egui::RawInput::default(), |ui| {
                fields.show(ui);
            });
            output.textures_delta.clear();
            let key = |key| egui::Event::Key {
                key,
                physical_key: None,
                pressed: true,
                repeat: false,
                modifiers: egui::Modifiers::NONE,
            };
            let events = vec![
                key(egui::Key::Num3),
                egui::Event::Text("3".into()),
                key(egui::Key::Tab),
            ];
            let mut output = context.run_ui(
                egui::RawInput {
                    events,
                    ..Default::default()
                },
                |ui| {
                    if retain_suffix {
                        retain_field_input_suffix(ui.ctx(), &[]);
                    } else {
                        ui.input_mut(|input| {
                            input.consume_key(egui::Modifiers::NONE, egui::Key::Tab);
                        });
                    }
                    ui.memory_mut(|memory| memory.request_focus(fields.ids()[0]));
                    result = fields.show(ui);
                },
            );
            output.textures_delta.clear();
            result
        }
        // Negative control reproduces the old whole-batch dispatch: the count
        // becomes field text simply because Tab focused its widget before draw.
        let old = draw_with_prefix(false);
        assert!(old.is_some() && old != Some(Ok(FramingPose::identity())));
        let fixed = draw_with_prefix(true);
        assert!(fixed.is_none() || fixed == Some(Ok(FramingPose::identity())));
    }

    #[test]
    fn camera_routing_preserves_native_text_ime_and_global_shortcuts() {
        use egui::{Key, Modifiers};
        for key in [
            Key::Enter,
            Key::Escape,
            Key::H,
            Key::ArrowUp,
            Key::Questionmark,
        ] {
            assert_eq!(
                dispatch_key(key, Modifiers::NONE, true, true, false, true, false),
                KeyDispatch::Native
            );
        }
        assert_eq!(
            dispatch_key(Key::Enter, Modifiers::NONE, true, false, false, true, false),
            KeyDispatch::Native
        );
        assert_eq!(
            dispatch_key(Key::Tab, Modifiers::NONE, true, false, false, true, false),
            KeyDispatch::Native
        );
        assert_eq!(
            dispatch_key(
                Key::Escape,
                Modifiers::NONE,
                true,
                false,
                false,
                true,
                false
            ),
            KeyDispatch::Deferred(CameraKey::Cancel)
        );
        assert_eq!(
            dispatch_key(
                Key::ArrowUp,
                Modifiers::NONE,
                true,
                false,
                false,
                true,
                false
            ),
            KeyDispatch::Deferred(CameraKey::Arrow(navigation::camera::Direction::Up))
        );
        assert_eq!(
            dispatch_key(
                Key::ArrowUp,
                Modifiers::SHIFT,
                true,
                false,
                false,
                true,
                false
            ),
            KeyDispatch::Native
        );
        assert_eq!(
            dispatch_key(
                Key::Enter,
                Modifiers::NONE,
                false,
                false,
                false,
                false,
                true
            ),
            KeyDispatch::Native
        );
        assert_eq!(
            dispatch_key(
                Key::Enter,
                Modifiers::NONE,
                false,
                false,
                false,
                false,
                false
            ),
            KeyDispatch::Draft(CameraKey::Commit)
        );
        assert_eq!(
            dispatch_key(
                Key::Questionmark,
                Modifiers::SHIFT,
                false,
                false,
                false,
                false,
                false
            ),
            KeyDispatch::Global
        );
        for text in [true, false] {
            let modifiers = Modifiers {
                mac_cmd: true,
                command: true,
                ..Modifiers::NONE
            };
            assert_eq!(
                dispatch_key(Key::Z, modifiers, text, false, false, text, false),
                if text {
                    KeyDispatch::Native
                } else {
                    KeyDispatch::Global
                }
            );
            let action = Bindings::default().key(Key::Z, modifiers, text, false);
            assert_eq!(action, (!text).then_some(Action::Undo));
        }
        for shift in [false, true] {
            let modifiers = Modifiers {
                mac_cmd: true,
                command: true,
                shift,
                ..Modifiers::NONE
            };
            // The general search/command focus helper does not know Camera's
            // widget IDs. Its false result cannot let native undo escape.
            assert_eq!(
                dispatch_key(Key::Z, modifiers, false, false, false, true, false),
                KeyDispatch::Native
            );
            assert_eq!(
                Bindings::default().key(Key::Z, modifiers, false, false),
                Some(if shift { Action::Redo } else { Action::Undo })
            );
        }
        let command = Modifiers {
            mac_cmd: true,
            command: true,
            ..Modifiers::NONE
        };
        for key in [Key::A, Key::C, Key::V, Key::X, Key::Enter] {
            assert_eq!(
                dispatch_key(key, command, false, false, false, true, false),
                KeyDispatch::Native
            );
        }
        for key in [Key::N, Key::O, Key::I] {
            assert_eq!(
                dispatch_key(key, command, false, false, false, true, false),
                KeyDispatch::Global
            );
        }
        assert_eq!(
            dispatch_key(Key::D, Modifiers::NONE, false, false, false, false, false),
            KeyDispatch::Draft(CameraKey::Other)
        );
    }

    fn pose(x: i64, scale: i64) -> FramingPose {
        FramingPose::new(
            ExactRatio::new(i128::from(x), 100).unwrap(),
            ExactRatio::new(1, 2).unwrap(),
            ExactRatio::new(i128::from(scale), 100).unwrap(),
        )
        .unwrap()
    }

    #[test]
    fn camera_adjusts_the_whole_curve_and_controls_without_changing_time_hosts() {
        let original = Framing::creep(
            pose(50, 100),
            pose(60, 135),
            FramingCurve::Cubic {
                control1: pose(45, 105),
                control2: pose(55, 120),
            },
        )
        .unwrap();
        let changed = adjusted_framing(Some(&original), pose(50, 100), pose(60, 200), false)
            .unwrap()
            .unwrap();
        let FramingValue::Envelope { envelope } = &changed.value else {
            panic!("curve collapsed")
        };
        assert_eq!(envelope.initial, pose(60, 200).quantized().unwrap());
        assert_eq!(envelope.segments[0].end, ExactRatio::ONE);
        assert_eq!(
            envelope.segments[0].pose,
            pose(70, 270).quantized().unwrap()
        );
        assert_eq!(
            envelope.segments[0].curve,
            FramingCurve::Cubic {
                control1: pose(55, 210).quantized().unwrap(),
                control2: pose(65, 240).quantized().unwrap(),
            }
        );
        assert_eq!(
            adjusted_framing(Some(&original), pose(50, 100), pose(50, 100), false).unwrap(),
            Some(original.clone())
        );
        assert_eq!(
            adjusted_framing(
                Some(&original),
                pose(50, 100),
                FramingPose::identity(),
                true
            )
            .unwrap(),
            None
        );
        let static_after_reset =
            adjusted_framing(Some(&original), pose(50, 100), pose(55, 150), true)
                .unwrap()
                .unwrap();
        assert_eq!(
            static_after_reset.value,
            FramingValue::Static {
                pose: pose(55, 150)
            }
        );
    }

    #[test]
    fn invalid_curve_adjustment_and_nonfinite_projection_fail_without_mutation() {
        let original =
            Framing::creep(pose(50, 100), pose(50, 4000), FramingCurve::Smoothstep).unwrap();
        let copy = original.clone();
        assert!(adjusted_framing(Some(&original), pose(50, 100), pose(50, 200), false).is_err());
        assert_eq!(original, copy);
        for value in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY, 1e30] {
            assert!(projected_ratio(value).is_err());
        }
        assert_eq!(
            projected_ratio(0.5).unwrap(),
            ExactRatio::new(1, 2).unwrap()
        );
        assert_eq!(
            projected_ratio(-0.25).unwrap(),
            ExactRatio::new(-1, 4).unwrap()
        );
    }
}
