"""Deterministic SDR VP9 MP4 fixtures using development-only libvpx.

Four lossless 12-picture inputs retain independently authored full/limited
8/10-bit patches and motion from generate_sdr_hevc_fixtures, plus mono AAC.
A 60-picture two-pass clip exercises hidden altref superframes and seeks.
--check compares regenerated bytes without changing the retained fixtures.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import struct
import tempfile
from generate_sdr_hevc_fixtures import planes, ROOT


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    audio = ROOT / 'fields-bff.mp4'
    assert hashlib.sha256(audio.read_bytes()).hexdigest() == 'ae843cb5d745c6e7076c46c26404161858df5eedf1644082d88d8f9e11f613aa'
    with tempfile.TemporaryDirectory(prefix='deadpan-vp9-') as directory:
        directory = Path(directory)
        cases = [(bits, full, False) for bits in [8, 10] for full in [False, True]]
        cases.append((8, False, True))
        for bits, full, altref in cases:
            name = 'vp9-altref.mp4' if altref else f'vp9-sdr-{bits}-' + ('full' if full else 'limited') + '.mp4'
            raw = directory / 'input.yuv'
            raw.write_bytes(b''.join(planes(bits, full, frame) for frame in range(60 if altref else 12)))
            output = directory / name
            command = ['ffmpeg', '-nostdin', '-v', 'error', '-f', 'rawvideo',
                '-pixel_format', 'yuv420p' if bits == 8 else 'yuv420p10le',
                '-video_size', '96x64', '-framerate', '30000/1001',
                '-color_range', 'pc' if full else 'tv', '-colorspace', 'bt709',
                '-color_trc', 'bt709', '-color_primaries', 'bt709',
                '-chroma_sample_location', 'left', '-i', str(raw)]
            if not altref:
                command += ['-i', str(audio), '-map', '0:v', '-map', '1:a', '-c:a', 'copy']
            command += ['-c:v', 'libvpx-vp9', '-threads', '1', '-row-mt', '0',
                '-deadline', 'good', '-cpu-used', '0', '-g', '30' if altref else '4',
                '-color_range', 'pc' if full else 'tv', '-colorspace', 'bt709',
                '-color_trc', 'bt709', '-color_primaries', 'bt709',
                '-chroma_sample_location', 'left', '-video_track_timescale', '60000',
                '-flags:v', '+bitexact', '-fflags', '+bitexact', '-movflags', '+faststart']
            if altref:
                command += ['-b:v', '100k', '-auto-alt-ref', '1', '-lag-in-frames', '25',
                    '-arnr-maxframes', '7', '-passlogfile', str(directory / 'pass')]
                subprocess.run(command + ['-pass', '1', '-an', '-f', 'null', '-y', '/dev/null'], check=True)
                command += ['-pass', '2']
            else:
                command += ['-lossless', '1', '-auto-alt-ref', '0', '-lag-in-frames', '0']
            subprocess.run(command + ['-y', str(output)], check=True)
            data = output.read_bytes()
            destination = ROOT / name
            if args.check:
                assert destination.read_bytes() == data, name
            else:
                destination.write_bytes(data)
            print(json.dumps({'name': name, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()}))
        for bits in [8, 10]:
            # A real one-byte show_existing_frame after a key that refreshed
            # all slots. IVF avoids hand-editing MP4 offsets or sample tables.
            source = directory / f'vp9-sdr-{bits}-limited.mp4'
            packets = json.loads(subprocess.check_output(['ffprobe', '-v', 'error',
                '-select_streams', 'v', '-show_packets', '-show_entries', 'packet=pos,size',
                '-of', 'json', str(source)]))['packets']
            first = packets[0]
            at, size = int(first['pos']), int(first['size'])
            key = source.read_bytes()[at:at + size]
            ivf = directory / 'existing.ivf'
            ivf.write_bytes(struct.pack('<4sHH4sHHIIII', b'DKIF', 0, 32, b'VP90', 96, 64,
                30000, 1001, 2, 0) + struct.pack('<IQ', len(key), 0) + key
                + struct.pack('<IQB', 1, 1, 0x88 if bits == 8 else 0x98))
            name = f'vp9-existing-{bits}.mp4'
            output = directory / name
            subprocess.run(['ffmpeg', '-nostdin', '-v', 'error', '-i', str(ivf),
                '-c:v', 'copy', '-color_range', 'tv', '-colorspace', 'bt709',
                '-color_trc', 'bt709', '-color_primaries', 'bt709', '-chroma_sample_location', 'left',
                '-video_track_timescale', '60000', '-fflags', '+bitexact', '-movflags', '+faststart',
                '-y', str(output)], check=True)
            data = output.read_bytes()
            if args.check:
                assert (ROOT / name).read_bytes() == data, name
            else:
                (ROOT / name).write_bytes(data)
            print(json.dumps({'name': name, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()}))


if __name__ == '__main__':
    main()
