from pathlib import Path
root = Path('/Users/michael/Code/deadpan')
old = (root / 'crates/deadpan-store/tests/migration/sequence_insert.rs').read_text()
end = old.index('\nfn silent_hold(')
text = old[:end].replace('use std::collections::BTreeMap;\n', '')
text = text.replace('sequence-insert-history', 'moment-splice-history')
text = text.replace('v31-', 'v32-').replace('schema31', 'schema32')
text = text.replace('retains_root_interiors', 'retains_nested_interiors')
text = text.replace('(26, 12)', '(32, 15)')
text = text.replace('MigrationRequired(31)', 'MigrationRequired(32)')
text = text.replace('(31, DATABASE_SCHEMA_VERSION)', '(32, DATABASE_SCHEMA_VERSION)')
text = text.replace('legacy_v25', 'legacy_v26')
text = text.replace('core25-pause', 'core26-pause').replace('core25-second-pause', 'core26-second-pause')
(root / 'crates/deadpan-store/tests/migration/moment_splice.rs').write_text(text)
