#![cfg(any(target_os = "macos", target_os = "linux"))]

use std::error::Error;
use std::fs;
use std::io::{Cursor, Read, Seek, SeekFrom};
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::sync::atomic::AtomicBool;
use std::time::Duration;

use deadpan_core::{
    ColorPolicy, FrameRate, NodeId, PresentationBasis, ProjectDocument, ProjectId, RevisionId,
};
use deadpan_store::generated_media::{
    GeneratedContentId, GeneratedMediaError, GeneratedMediaLimits, GeneratedObjectRef,
    GeneratedReadLimits,
};
use deadpan_store::{AccessMode, ProjectStore};

type Result<T = ()> = std::result::Result<T, Box<dyn Error>>;

fn document() -> Result<ProjectDocument> {
    Ok(ProjectDocument::new(
        ProjectId::new("generated-read-project")?,
        RevisionId::new("r0")?,
        PresentationBasis {
            width: 768,
            height: 320,
            frame_rate: FrameRate::new(30_000, 1_001)?,
            color_policy: ColorPolicy::SdrRec709,
        },
        NodeId::new("root")?,
    )?)
}

fn publish(store: &mut ProjectStore, bytes: &[u8]) -> Result<GeneratedObjectRef> {
    let reference = GeneratedObjectRef::new(
        GeneratedContentId::new(blake3::hash(bytes).to_hex().to_string())?,
        u64::try_from(bytes.len())?,
    )?;
    store.promote_generated_object(
        &mut Cursor::new(bytes),
        &reference,
        GeneratedMediaLimits::new(reference.byte_length())?,
    )?;
    Ok(reference)
}

fn limits() -> Result<GeneratedReadLimits> {
    Ok(GeneratedReadLimits::new(1_048_576, Duration::from_secs(5))?)
}

fn stored_path(package: &Path, reference: &GeneratedObjectRef) -> PathBuf {
    package
        .join("Media/Generated")
        .join(format!("blake3-{}", reference.content().digest()))
}

#[test]
fn cloned_handles_read_on_workers_without_retaining_the_writer_lock() -> Result {
    let scratch = tempfile::tempdir()?;
    let package = scratch.path().join("workers.deadpan");
    let initial = document()?;
    let mut store = ProjectStore::create(&package, &initial)?;
    let bytes = b"generated bytes for a connection-free worker";
    let expected = publish(&mut store, bytes)?;
    let handle = store.generated_read_handle();
    let worker_handle = handle.clone();
    let worker_expected = expected.clone();
    let worker_limits = limits()?;
    let worker = std::thread::spawn(move || {
        worker_handle.snapshot(&worker_expected, worker_limits, &AtomicBool::new(false))
    });
    assert_eq!(store.snapshot()?, initial);
    let mut snapshot = worker.join().expect("snapshot worker panicked")?;
    assert!(!handle.is_closed());
    drop(store);
    assert!(handle.is_closed());
    assert!(matches!(
        handle.snapshot(&expected, limits()?, &AtomicBool::new(false)),
        Err(GeneratedMediaError::SessionClosed)
    ));
    assert!(matches!(
        handle.check_live(&AtomicBool::new(true)),
        Err(GeneratedMediaError::SessionClosed)
    ));
    // Keeping both the handle and its immutable result cannot retain the lock.
    let reopened = ProjectStore::open(&package, AccessMode::ReadWrite)?;
    assert!(
        handle.is_closed(),
        "a new writer must not revive an old handle"
    );
    let mut observed = Vec::new();
    snapshot.read_to_end(&mut observed)?;
    assert_eq!(observed, bytes);
    assert!(!reopened.generated_read_handle().is_closed());
    Ok(())
}

#[test]
fn read_only_store_revokes_its_own_handles_independently_of_the_writer() -> Result {
    let scratch = tempfile::tempdir()?;
    let package = scratch.path().join("readonly.deadpan");
    let mut writer = ProjectStore::create(&package, &document()?)?;
    let bytes = b"read-only generated snapshot";
    let expected = publish(&mut writer, bytes)?;
    let reader = ProjectStore::open(&package, AccessMode::ReadOnly)?;
    let handle = reader.generated_read_handle();
    let clone = handle.clone();
    let writer_handle = writer.generated_read_handle();
    drop(writer);
    assert!(writer_handle.is_closed());
    assert!(!handle.is_closed());
    let mut snapshot = clone.snapshot(&expected, limits()?, &AtomicBool::new(false))?;
    drop(reader);
    assert!(handle.is_closed());
    assert!(clone.is_closed());
    assert!(matches!(
        clone.snapshot(&expected, limits()?, &AtomicBool::new(false)),
        Err(GeneratedMediaError::SessionClosed)
    ));
    let mut observed = Vec::new();
    snapshot.read_to_end(&mut observed)?;
    assert_eq!(observed, bytes);
    Ok(())
}

#[test]
fn read_handle_pins_the_package_namespace_across_path_replacement() -> Result {
    let scratch = tempfile::tempdir()?;
    let package = scratch.path().join("active.deadpan");
    let relocated = scratch.path().join("relocated.deadpan");
    let mut original = ProjectStore::create(&package, &document()?)?;
    let bytes = b"the originally opened package";
    let expected = publish(&mut original, bytes)?;
    let handle = original.generated_read_handle();
    fs::rename(&package, &relocated)?;
    let replacement = ProjectStore::create(&package, &document()?)?;
    let mut snapshot = handle.snapshot(&expected, limits()?, &AtomicBool::new(false))?;
    let mut observed = Vec::new();
    snapshot.read_to_end(&mut observed)?;
    assert_eq!(observed, bytes);
    assert!(matches!(
        replacement
            .generated_read_handle()
            .snapshot(&expected, limits()?, &AtomicBool::new(false)),
        Err(GeneratedMediaError::MissingObject(_))
    ));
    assert!(stored_path(&relocated, &expected).is_file());
    assert!(!stored_path(&package, &expected).exists());
    Ok(())
}

#[test]
fn immutable_handle_snapshot_survives_corruption_but_cold_read_rejects_it() -> Result {
    let scratch = tempfile::tempdir()?;
    let package = scratch.path().join("immutable.deadpan");
    let mut store = ProjectStore::create(&package, &document()?)?;
    let bytes = b"immutable generated bytes";
    let expected = publish(&mut store, bytes)?;
    let handle = store.generated_read_handle();
    let mut snapshot = handle.snapshot(&expected, limits()?, &AtomicBool::new(false))?;
    let path = stored_path(&package, &expected);
    fs::set_permissions(&path, fs::Permissions::from_mode(0o600))?;
    fs::write(&path, vec![b'x'; bytes.len()])?;
    fs::set_permissions(&path, fs::Permissions::from_mode(0o444))?;
    assert!(matches!(
        handle.snapshot(&expected, limits()?, &AtomicBool::new(false)),
        Err(GeneratedMediaError::HashMismatch { .. })
    ));
    drop(store);
    fs::remove_file(path)?;
    let mut observed = Vec::new();
    snapshot.read_to_end(&mut observed)?;
    assert_eq!(observed, bytes);
    snapshot.seek(SeekFrom::Start(0))?;
    observed.clear();
    snapshot.read_to_end(&mut observed)?;
    assert_eq!(observed, bytes);
    Ok(())
}

#[test]
fn read_budgets_and_cancellation_reject_work_before_unbounded_copying() -> Result {
    for (maximum_bytes, timeout) in [
        (0, Duration::from_secs(1)),
        (1, Duration::ZERO),
        (1, Duration::from_secs(3601)),
        (1, Duration::MAX),
    ] {
        assert!(matches!(
            GeneratedReadLimits::new(maximum_bytes, timeout),
            Err(GeneratedMediaError::InvalidReadLimits)
        ));
    }
    let scratch = tempfile::tempdir()?;
    let package = scratch.path().join("bounded.deadpan");
    let mut store = ProjectStore::create(&package, &document()?)?;
    let expected = publish(&mut store, b"bounded bytes")?;
    let handle = store.generated_read_handle();
    let short = GeneratedReadLimits::new(expected.byte_length() - 1, Duration::from_secs(1))?;
    assert_eq!(short.maximum_bytes(), expected.byte_length() - 1);
    assert_eq!(short.timeout(), Duration::from_secs(1));
    assert!(matches!(
        handle.snapshot(&expected, short, &AtomicBool::new(false)),
        Err(GeneratedMediaError::TooLarge { .. })
    ));
    fs::remove_file(stored_path(&package, &expected))?;
    assert!(matches!(
        handle.snapshot(&expected, limits()?, &AtomicBool::new(true)),
        Err(GeneratedMediaError::Cancelled)
    ));
    Ok(())
}
